spring:
  config:
    import: "optional:configserver:"  # Config Server와의 연동
  application:
    name: gate-way-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
        - name: RateLimiterFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2

  zipkin:
    base-url: http://localhost:9411

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka  # Eureka 서버 주소
    healthcheck:
      enabled: true  # Eureka 서버 상태 체크

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET_KEY}  # JWT 비밀 키
  expiration: 3600000  # JWT 만료 시간 (1시간)
