spring:
  config:
    import: "optional:configserver:"
  application:
    name: gate-way-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, info, metrics, prometheus